#!/usr/bin/env sh
set -e

url="https://raw.githubusercontent.com/webuni/shell-task-runner/master/runner"
[ -f ./.runner ] && [ .runner -nt "$0" ] || wget -q "$url" -O- > .runner || curl -fso .runner "$url"
. ./.runner

_decorator()( _decorator_docker_compose_run "$@" )

# Install dependencies
task_deps()( _run pip install --ignore-installed -e .[code,test] "sphinx==${SPHINX_VERSION:-3.*}" 2>&1 )

# Update dependencies to the latest versions
task_deps__latest()( _run pip install --ignore-installed --upgrade -e .[code,test] "sphinx==${SPHINX_VERSION:-3.*}" 2>&1 )

# Init virtual environment
# @service python
task_init() ( python3 -m venv ./venv/ ) # --system-site-packages

# Run pip
# @service python
task_pip()( pip3 "$@" )

# Run flit
# @service python
task_flit()( flit "$@" )

# Run tests
# @service python
task_tests()( pytest "$@" )

# Fix code style
# @service python
task_cs()( black . )

# Analyse code
# @service python
task_analyse()( mypy sphinxcontrib.kroki )

# Remove all containers in project (use -v to remove volumes also)
task_clean()( _docker_compose down --remove-orphans  "$@" )

# Run shell
# @service python
task_shell()( sh "$@" )
