name: Tests

on:
  push: ~
  pull_request: ~

jobs:
  pytest:
    name: Python on ${{ matrix.python }} and Sphinx ${{ matrix.sphinx }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python: [ "3.8", "3.9", "3.10", "3.11", "3.12" ]
        sphinx: [ "^4", "^5", "^6", "^7" ]
    steps:
      - uses: actions/checkout@v4
      - name: Set Up Python ${{ matrix.python }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Update build deps
        run: poetry run python -m pip install --upgrade pip setuptools
      - name: Install dependencies
        run: poetry install
      - name: Set sphinx version
        run: poetry add sphinx@${{ matrix.sphinx }}
      - name: Run Tests
        run: poetry run pytest
